//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPU.Hub.Server.WebAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("satya.jena@smartbitit.com")]
        public string AdminUser {
            get {
                return ((string)(this["AdminUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4O9uPSW+3HFFB7YquwKR/w==")]
        public string AdminPassword {
            get {
                return ((string)(this["AdminPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48ba69b975apa748e0bce2e64deed726519123e4c98909117046")]
        public string AdminPassword2 {
            get {
                return ((string)(this["AdminPassword2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lb2rfmQ2+mnUJmMvNcWOEQ6172ESD5BN7IAmjVacKIkBGQx+JZS44ekWuYV5IPII15jkEfprjDvaNvnX8" +
            "nDAfjPvcd0q8ct6m6ufQsOZgb2C/IDnEAbSaU5+Ac5EciyvnyBkqrd/Ea+tW6+4ye1LYDBj8nlczWAw0" +
            "SW1FJPKuwg=")]
        public string OPUConnectionString {
            get {
                return ((string)(this["OPUConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("adkls32659hp0dfjkasddf9084r90fe049xcvzxciosdlf0093458730345023894+72")]
        public string OPUConnectionString2 {
            get {
                return ((string)(this["OPUConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://orderpoint.smartbitit.com/opuwebui/cca/initiatepayment")]
        public string PaymentURI {
            get {
                return ((string)(this["PaymentURI"]));
            }
        }
    }
}
