//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPU.Hub.Server.WebUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XdnCZhUEkPKMwstqDPjQWbM0hkjb5DmQxMdkNTJXRxc=")]
        public string CCAvenueWorkingKey {
            get {
                return ((string)(this["CCAvenueWorkingKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1j2wO73xHIizB3mp2YnHRS3n28/xGDSHjYACZuR+e6g=")]
        public string CCAvenueAccessCode {
            get {
                return ((string)(this["CCAvenueAccessCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("166896")]
        public string CCAvenueMerchantId {
            get {
                return ((string)(this["CCAvenueMerchantId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INR")]
        public string CCAvenueCurrency {
            get {
                return ((string)(this["CCAvenueCurrency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://opu.smartbitit.com/opuwebui/CCA/CCAResponse")]
        public string CCAvenueRedirectUrl {
            get {
                return ((string)(this["CCAvenueRedirectUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string CCAvenueLanguage {
            get {
                return ((string)(this["CCAvenueLanguage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://opu.smartbitit.com/opuwebui/CCA/PaymentCancelled")]
        public string CCAvenueCancelUrl {
            get {
                return ((string)(this["CCAvenueCancelUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("satya.jena@smartbitit.com")]
        public string AdminUser {
            get {
                return ((string)(this["AdminUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lb2rfmQ2+mnUJmMvNcWOEQ6172ESD5BN7IAmjVacKIn51J4rPMmp/TvSbshTe6tZkrtotexVjOCQ2piyI" +
            "IAzFUybaqxb3PJMfsIjF08+72EUv6cWNR5lsUzlscIrYgz8")]
        public string OPUConnectionString {
            get {
                return ((string)(this["OPUConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("adkls32659hp0dfjkasddf9084r90fe049xcvzxciosdlf0093458730345023894+72")]
        public string OPUConnectionString2 {
            get {
                return ((string)(this["OPUConnectionString2"]));
            }
        }
    }
}
